# Generated by Django 5.1 on 2024-09-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Text of the quote")),
                (
                    "author",
                    models.CharField(
                        max_length=100, verbose_name="Author of the quote"
                    ),
                ),
            ],
        ),
    ]
